from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evaluation/real'
parts=['# Real filing evaluation\n','Evaluated September 21, 2026. All labels are agent-authored from source text, not independently human-reviewed. The held-out split was not used for retrieval tuning, but the author also built the system; this is not a blind external benchmark.\n','## Protocol\n','Four real filings; 1,309 passages. Sixty questions: 40 answerable and 20 unsupported. Each split has 20 answerable and 10 unsupported questions. Positive evidence families and paired paraphrases stay in one split. Questions and source index were hashed before new retrieval development. Training for LSA uses only source passages.\n','The original engine is preserved in `baselines/v1_engine.py` and evaluated against the same corrected real corpus. Thus these engine comparisons do not measure the separate parser improvement. BM25 was selected on development results, and implementation hashes were frozen before running held-out evaluation. No implementation changes followed held-out inspection.\n','Development changes: remove question filler, normalize the supply inflection, reject wrong financial measures, require currency evidence for monetary requests, check exact requested numbers and event-specific date precision, require explicit causal language, and require evidence from both selected filings. All methods share these gates. Retrieval budget is five passages total, distributed across both documents for comparisons.\n','## Results\n','Gold-complete means every annotated passage ID was cited. Alternate relevant passages count as misses. An exact quote is evidence of textual fidelity, not proof that it answers a question.\n','| Split | Engine | Gold retrieved /20 | Gold-complete answers /20 | Unsupported abstentions /10 | False abstentions /20 | Answered but not gold-complete | Complete comparisons |\n|---|---|---:|---:|---:|---:|---:|---:|']
for split in ['dev','heldout']:
 report=json.loads((E/f'{split}-results.json').read_text())
 for method,item in report['reports'].items():
  c=item['counts'];parts.append(f"| {split} | {method} | {c['retrieval_complete']} | {c['gold_answer_complete']} | {c['unsupported_abstained']} | {c['false_abstentions']} | {c['incorrect_answers']} | {c['complete_comparisons']}/{c['comparisons']} |")
parts+=['\nBM25 is the default because it led on development gold coverage. The corpus-fitted, 64-dimensional LSA model and reciprocal-rank hybrid did not improve the measured results. This experiment does not establish how a pretrained embedding model would perform.\n','Selected BM25 held-out results: 17/17 excerpts exactly matched their source passages and 0 excerpts crossed the selected company/filing scope. Human-verified semantic support remains **unmeasured**.\n','## Every selected-engine failure\n']
for split in ['dev','heldout']:
 parts.append('### '+split+'\n')
 for r in json.loads((E/f'{split}-results.json').read_text())['reports']['bm25']['results']:
  if r['outcome'] in {'gold_complete','correct_abstention'}:continue
  cited=', '.join(a['citation']['passage_id'] for a in r['result']['answer']) or 'none'
  parts.append(f"- **{r['id']} — {r['question']}** Outcome: `{r['outcome']}`; reason: `{r['result']['reason']}`. Gold: {', '.join(r['gold']) or 'unsupported'}. Cited: {cited}.")
parts+=['\n### Interpretation\n','- Development r37 cites another paragraph that mentions digital channels, direct sales and partners. It remains a strict gold miss; the frozen label was not expanded after seeing the result.\n- Held-out r03 cites another developer-ecosystem passage rather than the annotated integrations passage. This also remains a strict miss.\n- Six answerable held-out questions abstained. Morphological differences, additional question words, and required topic coverage make the gate overly conservative in these cases.\n- **Held-out r51 is an actual unsupported answer:** an exact U.S. headcount question received a generic employee-recruiting risk bullet. The quantity check does not recognize that question formulation, while token filtering drops geographic initials. This is a known correctness limitation, not a successful answer. It is preserved in the frozen report and has not been tuned away.\n','## Source audit\n','Twenty passages, five per filing, were compared in the browser against complete normalized text in the official SEC rendered page. All 20 excerpts matched exactly and all 20 source anchors existed. See `source-audit.json` for full quotes, source URLs, hashes and observations. This is a selected agent audit, not exhaustive or human-certified extraction validation.\n','The original parser produced 2,215 passages on these documents, including later sections incorrectly labeled as MD&A or risks. Fixes recognize plain-div Item headings as boundaries, prevent prose references from changing sections, remove recurring Docusign page headers, and retain the nearest real source anchor. Corrected output: 1,309 passages. Tables remain deliberately excluded. Some long or page-split paragraphs retain incomplete surrounding context; source inspection is necessary.\n','## Artifacts and reproduction\n','- `frozen.json`: question and corpus hashes.\n- `selection.json`: selected method, rationale and pre-held-out implementation hashes.\n- `dev-results.json`, `heldout-results.json`: every question, retrieval result, excerpt and outcome for every engine.\n- `source-audit.json`: complete twenty-passage source comparison.\n- `web-verification.json`: API and browser evidence.\n- `../../VALIDATION.md`: commands and exit statuses.\n','From the project directory: `python3 -m filing_assistant.real_eval dev` and `python3 -m filing_assistant.real_eval heldout`. Repeating held-out evaluation reproduces a known result; it does not create a fresh test set. Do not regenerate questions or source index to improve a score.\n']
(E/'REPORT.md').write_text('\n'.join(parts)+'\n')
